version: '3.8'


services:
  db:
    image: postgres:12.5
    volumes:
      - business_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - 5432:5432
  web:
    build: ./config
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./config/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      
volumes:
  business_postgres_data: