# Generated by Django 3.1.5 on 2021-01-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='citizen',
            field=models.ManyToManyField(related_name='citizen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='mayor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mayor', to=settings.AUTH_USER_MODEL),
        ),
    ]
